### ISSUE TITLE
Warcraft 3 crashing when launching SharpCraft

### ISSUE THREAD

**Issue by ttay24** [TinkerWorX/SharpCraft#33]
![image](https://cloud.githubusercontent.com/assets/4239808/22173329/2eb1d2f0-df85-11e6-9049-7d20e50b30a9.png)

I'm trying to follow this tutorial, http://imgur.com/a/UG9ig,  but I'm getting errors when launching SharpCraft (specifically "Start game windowed (debug).bat"). Any clue what could be the cause? I'm running the latest release: v4.0.0.160

**Comment by TinkerWorX** [comment]
Can you confirm which version of Warcraft III you are trying to use it with? Should be the full text you can find if you open properties for war3.exe and open the Details tab.

**Comment by ttay24** [comment]
I'm using the latest version, 1.27.1.7085

**Comment by TinkerWorX** [comment]
That's the problem then, the version you're using only works with 1.27.0.52240.

I'm working on a new version that works differently, it'll be out in a few days, which also works with the most recent version.

**Comment by ttay24** [comment]
oh okay, sweet! Thanks for the fast response. I'm new to SharpCraft. So essentially, you can write "plugins", or dll's, that you can call from JASS, so you can extend functionality of war3? Is that kind of the gist? Other question is can you play over b.net with stuff hooked into it, or is that a bad idea/you should write separate networking to handle multiplayer from single player?Also you can close this issue now. Thanks for your help!

**Comment by TinkerWorX** [comment]
Yeah, pretty much. SharpCraft is simply the system that loads up plugins and handles dependencies. It's then up to the plugins to do various things. I've made the plugins needed to add new natives and interact with the JASS engine, which will be bundled with the next release. You can use SharpCraft online, however, you need to be careful with desyncing things. One example is input from the user. If you detect a mouse click and run some JASS based on it, it'll desync because the mouse click isn't sent to the other players. There are definitely challenges involved. Emulating multiplayer through singleplayer is another approach which both me and others have done before, which is more work, but also much more reliable and flexible if done correctly.

With the new version I'll make a new tutorial. I've changed things up a bit, and I'm using a framework called MEF to handle the loading of plugins.

**Comment by ttay24** [comment]
Sweet, thanks for the response!
